CPMAddPackage(
  NAME SDL
  GITHUB_REPOSITORY libsdl-org/SDL
  VERSION 3.2.14
  GIT_TAG release-3.2.14
  OPTIONS
    "BUILD_SHARED_LIBS ${BUILD_SHARED_LIBS}"
    "SDL_RENDER ON"
    "CMAKE_POSITION_INDEPENDENT_CODE ON"
)
