if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()

function(unigui_verify_document_anchor target_file anchor source_file)
    string(TOLOWER "${anchor}" expected_anchor)
    file(STRINGS "${target_file}" heading_lines REGEX "^#+[ \t]+")
    set(anchor_found FALSE)
    foreach(heading_line IN LISTS heading_lines)
        string(REGEX REPLACE "^#+[ \t]+" "" heading "${heading_line}")
        string(TOLOWER "${heading}" heading_slug)
        string(REGEX REPLACE "[^a-z0-9 _-]" "" heading_slug "${heading_slug}")
        string(REGEX REPLACE "[ \t]+" "-" heading_slug "${heading_slug}")
        if(heading_slug STREQUAL expected_anchor)
            set(anchor_found TRUE)
            break()
        endif()
    endforeach()
    if(NOT anchor_found)
        file(RELATIVE_PATH target_relative "${SOURCE_DIR}" "${target_file}")
        file(RELATIVE_PATH source_relative "${SOURCE_DIR}" "${source_file}")
        message(FATAL_ERROR
            "Broken documentation anchor #${anchor} in ${source_relative}: ${target_relative}")
    endif()
endfunction()

file(GLOB NODE_DOCUMENTS LIST_DIRECTORIES FALSE "${SOURCE_DIR}/docs/nodes/*.md")
set(DOCUMENTS
    "${SOURCE_DIR}/README.md"
    "${SOURCE_DIR}/CHANGELOG.md"
    "${SOURCE_DIR}/docs/ABI_POLICY.md"
    ${NODE_DOCUMENTS}
)

set(VERIFIED_LINK_COUNT 0)
foreach(DOCUMENT IN LISTS DOCUMENTS)
    if(NOT EXISTS "${DOCUMENT}" OR IS_DIRECTORY "${DOCUMENT}")
        file(RELATIVE_PATH missing_relative "${SOURCE_DIR}" "${DOCUMENT}")
        message(FATAL_ERROR "Documentation file is missing: ${missing_relative}")
    endif()
    file(SIZE "${DOCUMENT}" document_size)
    if(document_size EQUAL 0)
        file(RELATIVE_PATH empty_relative "${SOURCE_DIR}" "${DOCUMENT}")
        message(FATAL_ERROR "Documentation file is empty: ${empty_relative}")
    endif()

    get_filename_component(DOCUMENT_DIRECTORY "${DOCUMENT}" DIRECTORY)
    file(STRINGS "${DOCUMENT}" DOCUMENT_LINES)
    set(IN_CODE_FENCE FALSE)
    foreach(DOCUMENT_LINE IN LISTS DOCUMENT_LINES)
        if(DOCUMENT_LINE MATCHES "^```")
            if(IN_CODE_FENCE)
                set(IN_CODE_FENCE FALSE)
            else()
                set(IN_CODE_FENCE TRUE)
            endif()
            continue()
        endif()
        if(IN_CODE_FENCE)
            continue()
        endif()

        string(REGEX MATCHALL "\\[[^][]+\\]\\([^)]+\\)" DOCUMENT_LINKS "${DOCUMENT_LINE}")
        foreach(DOCUMENT_LINK IN LISTS DOCUMENT_LINKS)
            string(REGEX REPLACE "^.*\\]\\(([^)]+)\\)$" "\\1"
                LINK_TARGET "${DOCUMENT_LINK}")
            if(LINK_TARGET MATCHES "^(https?://|mailto:)")
                continue()
            endif()

            set(LINK_PATH "${LINK_TARGET}")
            set(LINK_ANCHOR "")
            if(LINK_TARGET MATCHES "^([^#]*)#(.+)$")
                set(LINK_PATH "${CMAKE_MATCH_1}")
                set(LINK_ANCHOR "${CMAKE_MATCH_2}")
            endif()
            if(LINK_PATH STREQUAL "")
                set(ABSOLUTE_TARGET "${DOCUMENT}")
            else()
                get_filename_component(ABSOLUTE_TARGET "${LINK_PATH}" ABSOLUTE
                    BASE_DIR "${DOCUMENT_DIRECTORY}")
            endif()
            if(NOT EXISTS "${ABSOLUTE_TARGET}" OR IS_DIRECTORY "${ABSOLUTE_TARGET}")
                file(RELATIVE_PATH source_relative "${SOURCE_DIR}" "${DOCUMENT}")
                message(FATAL_ERROR
                    "Broken documentation link in ${source_relative}: ${LINK_TARGET}")
            endif()
            if(NOT LINK_ANCHOR STREQUAL "")
                unigui_verify_document_anchor(
                    "${ABSOLUTE_TARGET}" "${LINK_ANCHOR}" "${DOCUMENT}")
            endif()
            math(EXPR VERIFIED_LINK_COUNT "${VERIFIED_LINK_COUNT} + 1")
        endforeach()
    endforeach()
endforeach()

message(STATUS "Verified ${VERIFIED_LINK_COUNT} local documentation links and anchors")
